# Generated by Django 4.0 on 2022-01-02 19:15

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeilingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('foto', models.ImageField(upload_to=main.models.path_foto)),
            ],
        ),
        migrations.CreateModel(
            name='CorniceModel',
            fields=[
                ('ceilingmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.ceilingmodel')),
            ],
            options={
                'verbose_name': 'Карниз',
                'verbose_name_plural': 'Карнизы',
            },
            bases=('main.ceilingmodel',),
        ),
        migrations.CreateModel(
            name='LightModel',
            fields=[
                ('ceilingmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.ceilingmodel')),
                ('type_light', models.CharField(choices=[('CHANDELIER', 'люстры'), ('TRACK_AND_SPOT', 'треки и споты'), ('LEDLAMP_AND_POINT', 'LED-светильники и точечные'), ('LEDPANEL', 'LED-панели'), ('LED_STRIP_LIGHT', 'LED-ленты и комплектующие')], default='CH', max_length=30)),
            ],
            options={
                'verbose_name': 'Освещение',
                'verbose_name_plural': 'Освещения',
            },
            bases=('main.ceilingmodel',),
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('ceilingmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.ceilingmodel')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиля',
            },
            bases=('main.ceilingmodel',),
        ),
    ]
